# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker image prune --all
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-api-feed azumahjoshua/udagram-api-feed:v2
    - run: docker tag udagram-api-user azumahjoshua/udagram-api-user:v2
    - run: docker tag udagram-frontend:local azumahjoshua/udagram-frontend:v6
    - run: docker tag reverseproxy azumahjoshua/reverseproxy:v2
    - run: docker push azumahjoshua/udagram-frontend:v6
    - run: docker push azumahjoshua/udagram-api-user:v2
    - run: docker push azumahjoshua/udagram-api-feed:v2
    - run: docker push azumahjoshua/reverseproxy:v2

